package com.king.greenDAO.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.king.greenDAO.bean.User;
import com.king.greenDAO.bean.GeoModel;
import com.king.greenDAO.bean.Position;

import com.king.greenDAO.dao.UserDao;
import com.king.greenDAO.dao.GeoModelDao;
import com.king.greenDAO.dao.PositionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig geoModelDaoConfig;
    private final DaoConfig positionDaoConfig;

    private final UserDao userDao;
    private final GeoModelDao geoModelDao;
    private final PositionDao positionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        geoModelDaoConfig = daoConfigMap.get(GeoModelDao.class).clone();
        geoModelDaoConfig.initIdentityScope(type);

        positionDaoConfig = daoConfigMap.get(PositionDao.class).clone();
        positionDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        geoModelDao = new GeoModelDao(geoModelDaoConfig, this);
        positionDao = new PositionDao(positionDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(GeoModel.class, geoModelDao);
        registerDao(Position.class, positionDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        geoModelDaoConfig.getIdentityScope().clear();
        positionDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public GeoModelDao getGeoModelDao() {
        return geoModelDao;
    }

    public PositionDao getPositionDao() {
        return positionDao;
    }

}
